# Model Inspection

This notebook loads the trained model and explores:
- model coefficients
- feature importance (linear)
- interpretation of model behavior

In [12]:
import joblib
import sys
import pandas as pd
from pathlib import Path

current = Path().resolve()

# project root
while current != current.parent:
    if (current / 'src').exists():
        PROJECT_ROOT = current
        break
    current = current.parent

MODEL_DIR = PROJECT_ROOT / 'model'

In [13]:
data_rent = joblib.load(MODEL_DIR / 'rent_model_bundle.pkl')
data_buy = joblib.load(MODEL_DIR /  'buy_model_bundle.pkl')

print(data_rent)
print(data_buy)

{'model': LinearRegression(), 'imputer': SimpleImputer(strategy='median'), 'features': ['size_sqm', 'density_city', 'listings_per_1k_bundesland', 'listings_per_1k_city', 'city_te', 'object_type_te'], 'target': 'price_per_sqm', 'segment': 'zur Miete'}
{'model': LinearRegression(), 'imputer': SimpleImputer(strategy='median'), 'features': ['size_sqm', 'density_city', 'listings_per_1k_bundesland', 'listings_per_1k_city', 'city_te', 'object_type_te'], 'target': 'price_per_sqm', 'segment': 'zum Kauf'}

In [14]:
df_info = pd.DataFrame({
    'feature': data_rent['features'],
    'coef': data_rent['model'].coef_
})

df_info

                      feature      coef
0                    size_sqm -0.026537
1                density_city -0.000032
2  listings_per_1k_bundesland  0.000109
3        listings_per_1k_city  0.001922
4                     city_te  0.862818
5              object_type_te  0.364145

In [15]:
df_info = pd.DataFrame({
    'feature': data_buy['features'],
    'coef': data_buy['model'].coef_
})

df_info

                      feature       coef
0                    size_sqm  10.865752
1                density_city   0.112118
2  listings_per_1k_bundesland   0.048472
3        listings_per_1k_city  -1.309501
4                     city_te   0.911318
5              object_type_te   0.399594

### Interpretation

- Positive coefficient → increases price per sqm  
- Negative coefficient → decreases price per sqm  

Market saturation shows a negative effect, consistent with supply-demand theory.